version: "3.8"
services:
  HelloWordApp:
    image: eddytnk/myapp:latest
    secrets:
      - hello_world_message
    environment:
      HELLO_MESSAGE=/run/secrets/hello_world_message
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/hello-word/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

secret:
  hello_world_message:
    file: ./hello_world_message.txt
